<?php

if( ! defined('ABSPATH' )) {
    exit('Direct File access not allow!');
}

get_header(); ?>
<section class="hero-single-blog hero-bg">
    <div class="container">
        <div class="blog-hero-content text-center">

            <div class="hero-badge d-flex flex-wrap justify-center">

                <?php $categories = get_the_category();
                if (!empty($categories)):
                    foreach ($categories as $index => $category): ?>
                        <a
                            href="<?php echo esc_url(get_category_link($category->term_id)); ?>"><span><?php esc_html_e($category->name); ?></span></a>
                    <?php endforeach; endif; ?>
            </div>

            <h1><?php the_title(); ?></h1>
            <p><?php echo get_the_excerpt(); ?></p>

            <div class="sb-post-meta flex-center">
                <span class="sb-post-date"><?php echo get_the_date('F j, Y'); ?></span>
                <span
                    class="sb-post-author"><?php echo get_the_author_meta('display_name', get_current_blog_id()); ?></span>
            </div>
            <?php if (has_post_thumbnail()):
                $thumbnail_url = get_the_post_thumbnail_url(get_the_ID(), 'full'); ?>
                <div class="sb-blog-feature">
                    <img src="<?php echo esc_url($thumbnail_url); ?>" alt="<?php echo esc_attr(get_the_title()); ?>">
                </div>
            <?php endif; ?>

        </div>
    </div>
</section>
<!-- Hero Single Blog  -->


<section class="sb-single-blog-contents">
    <div class="container">
        <div class="sb-single-blog-content-wrapper d-flex align-start">

            <!-- Table Of Content Work On js  -->
            <div id="sb-table-content" class="sb-table-content text-center">
                <h3 class="sb-table-content-title">Table of Contents</h3>
                <ul>
                    <li><a href="#">Harness the Power of Social Media</a></li>
                    <li class="sb-tb-active"><a href="#">Craft a High -Converting Website</a></li>
                    <li><a href="#">Champion Content Marketing</a></li>
                </ul>
            </div>

            <div id="sb-blog-content" class="sb-blog-content">

                <div class="sb-summery-generate d-flex flex-col justify-center">
                    <div class="sb-summery-title-icon flex-center">
                        <h3>Summary Generated By</h3>
                        <img src="<?php echo get_theme_file_uri('/assets/images/SalonBoss-Ai-Logo.png') ?>" alt="Image">
                    </div>
                    <?php wp_kses_post(the_field('single_blog_post_content')); ?>
                </div><!-- sb summery generate  -->

                <?php
                echo get_the_content(); ?>

            </div>

            <!-- sidebar Come From Option  -->
            <div class="sb-blog-sidebar-box  text-center">

                <?php
                $logo = get_field('logo', 'options');
                $logourl = !empty($logo['url']) ? esc_url($logo['url']) : esc_url(get_theme_file_uri('/assets/images/Salon-Boss-logo.png'));
                $blog_page_info = get_field('blog_page_info', 'options');
                ?>
                <img src="<?php echo esc_url($logourl) ?>" alt="Logo">
                <p>The #1 Marketing Agency for the Hair & Beauty Industry</p>
                <?php if (!empty($blog_page_info['page_links'])):
                    foreach ($blog_page_info['page_links'] as $index => $item): // Use $index to keep track of the current index
                        $button_class = ($index % 2 === 0) ? 'button-bg-green' : 'button-bg-pink'; // Alternate classes
                        ?>
                        <a href="<?php echo esc_url(get_the_permalink($item->ID)); ?>"
                            class="sb-button <?php echo esc_attr($button_class); ?> icon-position-left button-icon-phone">
                            <?php echo esc_html(get_the_title($item->ID)); ?>
                        </a>
                    <?php endforeach;
                endif; ?>

            </div>
        </div>
    </div>
</section><!-- Single Blog Content  -->

<section class="sb-single-blog-author">
    <div class="container">
        <div class="sb-author-card">
            <div class="sb-author-card-content-wrapper d-flex">
                <?php
                $author_id = get_the_author_meta('ID', get_current_blog_id());
                ; ?>
                <div class="sb-author-card-image flex-center relative">
                    <?php
                    $author_image = get_avatar_url($author_id);
                    ?>
                    <img src="<?php echo esc_url($author_image); ?>" alt="<?php echo esc_attr(get_the_author()); ?>">
                    <div class="sb-author-card-badge text-center">
                        <h5><?php echo esc_html(get_the_author_meta('display_name', $author_id)); ?></h5>
                        <h6><?php echo esc_html(get_the_author_meta('nickname', $author_id)); ?></h6>
                    </div>
                </div>
                <div class="sb-author-card-content flex-center flex-col text-center">
                    <p>
                        <?php
                        echo esc_html(get_the_author_meta('description', $author_id)); ?>
                    </p>
                    <a target="_blank"
                        href="<?php echo esc_url(get_the_author_meta('user_url', $author_id) ?? site_url()); ?>">
                        Learn More About <?php echo esc_html(get_the_author_meta('first_name', $author_id)); ?> & Salon
                        Boss >
                    </a>
                </div>
            </div>
        </div><!-- Sb Author Card  -->
    </div>
</section>

<section class="sb-related-post">
    <div class="container">

        <div class="sb-section-title text-center">
            <h2>Related <span>Posts</span></h2>
        </div>

        <div class="sb-related-post-list">
            <?php
            $current_post_id = get_the_ID();
            $categories = wp_get_post_categories($current_post_id);

            if (!empty($categories)) {
                $related_posts_query = new WP_Query(array(
                    'category__in' => $categories,
                    'post__not_in' => array($current_post_id)
                ));

                if ($related_posts_query->have_posts()):
                    while ($related_posts_query->have_posts()):
                        $related_posts_query->the_post();
                        ?>
                        <div class="related-post-item">
                            <div class="sb-post-card sb-card sb-card-filled-bg">
                                <div class="sb-card-contents-wrapper">
                                    <div class="sb-card-image flex-center">
                                        <a href="<?php the_permalink(); ?>">
                                            <?php if (has_post_thumbnail()): ?>
                                                <img src="<?php echo get_the_post_thumbnail_url(get_the_ID(), 'full'); ?>"
                                                    alt="<?php echo esc_attr(get_the_title()); ?>">
                                            <?php endif; ?>
                                        </a>
                                    </div>
                                    <div class="sb-card-content text-center">
                                        <ul class="unstyle d-flex flex-wrap">
                                            <?php
                                            $post_categories = get_the_category();
                                            foreach ($post_categories as $category) {
                                                echo '<li><a href="' . get_category_link($category->term_id) . '">' . esc_html($category->name) . '</a></li>';
                                            }
                                            ?>
                                        </ul>
                                        <a class="sb-blog-title" href="<?php the_permalink(); ?>">
                                            <h3><?php the_title(); ?></h3>
                                        </a>
                                        <span class="sb-blog-date"><?php echo get_the_date(); ?></span>
                                        <div class="sb-card-btn">
                                            <a href="<?php the_permalink(); ?>">Read Article &gt;</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- Sb post card Item -->
                        <?php
                    endwhile;
                    wp_reset_postdata();
                endif;
            }
            ?>
        </div>
    </div>
</section><!-- Sb related post  -->

<?php get_footer(); ?>